#!/usr/bin/env bash
# SDD Init Script — Linux/macOS Bash
# Menginisialisasi project konversi baru dengan framework SDD
#
# Usage:
#   ./scripts/sdd-init.sh
#   ./scripts/sdd-init.sh --source-lang php --source-framework laravel --target-lang go --target-framework gin

set -e

# ─────────────────────────────────────────────
# Colors
# ─────────────────────────────────────────────
CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; GRAY='\033[0;37m'; NC='\033[0m'
header() { echo -e "\n${CYAN}🔷 $1${NC}"; }
success() { echo -e "  ${GREEN}✅ $1${NC}"; }
info() { echo -e "  ${GRAY}ℹ️  $1${NC}"; }
warn() { echo -e "  ${YELLOW}⚠️  $1${NC}"; }

echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}   ⚡ AlihSpec — Project Conversion Init${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# ─────────────────────────────────────────────
# Parse args or prompt
# ─────────────────────────────────────────────
PROJECT_NAME="${PROJECT_NAME:-}"
SOURCE_LANG="${SOURCE_LANG:-}"
SOURCE_FRAMEWORK="${SOURCE_FRAMEWORK:-}"
TARGET_LANG="${TARGET_LANG:-}"
TARGET_FRAMEWORK="${TARGET_FRAMEWORK:-}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --project-name) PROJECT_NAME="$2"; shift 2 ;;
    --source-lang) SOURCE_LANG="$2"; shift 2 ;;
    --source-framework) SOURCE_FRAMEWORK="$2"; shift 2 ;;
    --target-lang) TARGET_LANG="$2"; shift 2 ;;
    --target-framework) TARGET_FRAMEWORK="$2"; shift 2 ;;
    *) shift ;;
  esac
done

[ -z "$PROJECT_NAME" ] && read -p "📛 Project name: " PROJECT_NAME
[ -z "$SOURCE_LANG" ] && read -p "🔵 Source language (e.g., php, python, ruby, java): " SOURCE_LANG
[ -z "$SOURCE_FRAMEWORK" ] && read -p "🔵 Source framework (e.g., laravel, django, rails): " SOURCE_FRAMEWORK
[ -z "$TARGET_LANG" ] && read -p "🟢 Target language (e.g., go, typescript, python): " TARGET_LANG
[ -z "$TARGET_FRAMEWORK" ] && read -p "🟢 Target framework (e.g., gin, nestjs, fastapi): " TARGET_FRAMEWORK

# ─────────────────────────────────────────────
# Preset
# ─────────────────────────────────────────────
PRESET_KEY="${SOURCE_FRAMEWORK}-to-${TARGET_FRAMEWORK}"
PRESET_PATH=".sdd/presets/${PRESET_KEY}"

header "Checking preset: ${PRESET_KEY}"

if [ -d "$PRESET_PATH" ]; then
    success "Preset found: ${PRESET_KEY}"
    cp "${PRESET_PATH}/patterns.md" ".sdd/mapping/patterns.md"
    cp "${PRESET_PATH}/conventions.md" ".sdd/mapping/conventions.md"
    cp "${PRESET_PATH}/conventions.md" "context/conventions.md"
    if [ -f "${PRESET_PATH}/glossary.md" ]; then
        cp "${PRESET_PATH}/glossary.md" "context/glossary.md"
        success "Copied glossary.md to context/"
    fi
    success "Copied patterns.md, conventions.md, and glossary.md from preset"
else
    warn "No preset found for '${PRESET_KEY}'"
    info "Available presets:"
    ls .sdd/presets/ | while read d; do info "  - $d"; done
    warn "Fill .sdd/mapping/ and context/ manually"
fi

# ─────────────────────────────────────────────
# Update config.yaml
# ─────────────────────────────────────────────
header "Updating .sdd/config.yaml..."
DATE=$(date +%Y-%m-%d)

cat > .sdd/config.yaml << EOF
# SDD Framework Configuration
# Auto-generated by sdd-init.sh on ${DATE}

project:
  name: "${PROJECT_NAME}"
  description: "Converting ${PROJECT_NAME} from ${SOURCE_FRAMEWORK} (${SOURCE_LANG}) to ${TARGET_FRAMEWORK} (${TARGET_LANG})"
  version: "1.0.0"
  author: ""
  created_at: "${DATE}"

conversion:
  source:
    language: "${SOURCE_LANG}"
    framework: "${SOURCE_FRAMEWORK}"
    version: ""
    path: "./source"

  target:
    language: "${TARGET_LANG}"
    framework: "${TARGET_FRAMEWORK}"
    version: ""
    path: "./output"

scale:
  size: "medium"
  use_phases: true
  estimated_tasks: 0

ai:
  context_file: "./context/AGENTS.md"
  auto_update_tasks: true
  preferred_ides:
    - antigravity
    - kiro
    - cursor
    - copilot

mapping:
  preset_used: "${PRESET_KEY}"

output:
  structure: "idiomatic"
EOF

success "config.yaml updated"

# ─────────────────────────────────────────────
# Update AGENTS.md
# ─────────────────────────────────────────────
header "Updating context/AGENTS.md..."
sed -i "s|\[Source Language / Framework\] (located in \`source/\`)|${SOURCE_FRAMEWORK} (${SOURCE_LANG}) (located in \`source/\`)|g" context/AGENTS.md
sed -i "s|\[Target Language / Framework\] (output goes in \`output/\`)|${TARGET_FRAMEWORK} (${TARGET_LANG}) (output goes in \`output/\`)|g" context/AGENTS.md
success "AGENTS.md updated"

# ─────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}   ✅ AlihSpec Framework Initialized!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Project : ${PROJECT_NAME}"
echo -e "  From    : ${CYAN}${SOURCE_FRAMEWORK} (${SOURCE_LANG})${NC}"
echo -e "  To      : ${GREEN}${TARGET_FRAMEWORK} (${TARGET_LANG})${NC}"
echo "  Preset  : ${PRESET_KEY}"
echo ""
echo -e "${YELLOW}  Next steps:${NC}"
echo "  1. Copy your source project to source/"
echo "  2. Fill in context/AGENTS.md → Source Project Notes"
echo "  3. Read context/checklist-before-start.md"
echo "  4. Vibe coding? Open context/VIBE.md for ready-to-use prompts"
echo ""
