# SDD Init Script — Windows PowerShell
# Menginisialisasi project konversi baru dengan framework SDD
#
# Usage:
#   .\sdd-init.ps1
#   .\sdd-init.ps1 -SourceLang php -SourceFramework laravel -TargetLang go -TargetFramework gin

param(
    [string]$ProjectName = "",
    [string]$SourceLang = "",
    [string]$SourceFramework = "",
    [string]$TargetLang = "",
    [string]$TargetFramework = ""
)

# ─────────────────────────────────────────────
# Colors
# ─────────────────────────────────────────────
function Write-Header { param($msg) Write-Host "`n🔷 $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "  ✅ $msg" -ForegroundColor Green }
function Write-Info { param($msg) Write-Host "  ℹ️  $msg" -ForegroundColor Gray }
function Write-Warn { param($msg) Write-Host "  ⚠️  $msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "   ⚡ AlihSpec — Project Conversion Init" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

# ─────────────────────────────────────────────
# Collect info if not provided
# ─────────────────────────────────────────────
if (-not $ProjectName) {
    $ProjectName = Read-Host "📛 Project name (e.g., my-shop-api)"
}
if (-not $SourceLang) {
    $SourceLang = Read-Host "🔵 Source language (e.g., php, python, ruby, java, javascript)"
}
if (-not $SourceFramework) {
    $SourceFramework = Read-Host "🔵 Source framework (e.g., laravel, django, rails, spring, express)"
}
if (-not $TargetLang) {
    $TargetLang = Read-Host "🟢 Target language (e.g., go, typescript, python, java)"
}
if (-not $TargetFramework) {
    $TargetFramework = Read-Host "🟢 Target framework (e.g., gin, nestjs, fastapi, spring)"
}

# ─────────────────────────────────────────────
# Determine preset key
# ─────────────────────────────────────────────
$presetKey = "$SourceFramework-to-$TargetFramework"
$presetPath = ".sdd\presets\$presetKey"
$presetExists = Test-Path $presetPath

Write-Header "Checking preset: $presetKey"

if ($presetExists) {
    Write-Success "Preset found: $presetKey"
} else {
    Write-Warn "No exact preset found for '$presetKey'"
    Write-Info "Available presets:"
    Get-ChildItem ".sdd\presets" -Directory | ForEach-Object { Write-Info "  - $($_.Name)" }
    Write-Warn "Will use empty mapping files. Fill them manually in .sdd\mapping\"
}

# ─────────────────────────────────────────────
# Apply preset
# ─────────────────────────────────────────────
Write-Header "Applying preset mapping..."

if ($presetExists) {
    Copy-Item "$presetPath\patterns.md" ".sdd\mapping\patterns.md" -Force
    Copy-Item "$presetPath\conventions.md" ".sdd\mapping\conventions.md" -Force
    # Also update context/ files that are auto-generated from presets
    Copy-Item "$presetPath\conventions.md" "context\conventions.md" -Force
    if (Test-Path "$presetPath\glossary.md") {
        Copy-Item "$presetPath\glossary.md" "context\glossary.md" -Force
        Write-Success "Copied glossary.md to context/"
    }
    Write-Success "Copied patterns.md, conventions.md, and glossary.md from preset"
} else {
    Write-Info "Skipping preset copy — no matching preset"
}

# ─────────────────────────────────────────────
# Update config.yaml
# ─────────────────────────────────────────────
Write-Header "Updating .sdd/config.yaml..."

$date = Get-Date -Format "yyyy-MM-dd"
$configContent = @"
# SDD Framework Configuration
# Auto-generated by sdd-init.ps1 on $date

project:
  name: "$ProjectName"
  description: "Converting $ProjectName from $SourceFramework ($SourceLang) to $TargetFramework ($TargetLang)"
  version: "1.0.0"
  author: ""
  created_at: "$date"

conversion:
  source:
    language: "$SourceLang"
    framework: "$SourceFramework"
    version: ""
    path: "./source"

  target:
    language: "$TargetLang"
    framework: "$TargetFramework"
    version: ""
    path: "./output"

scale:
  size: "medium"
  use_phases: true
  estimated_tasks: 0

ai:
  context_file: "./context/AGENTS.md"
  auto_update_tasks: true
  preferred_ides:
    - antigravity
    - kiro
    - cursor
    - copilot

mapping:
  patterns_file: "./.sdd/mapping/patterns.md"
  conventions_file: "./.sdd/mapping/conventions.md"
  preset_used: "$presetKey"

output:
  structure: "idiomatic"
"@

Set-Content ".sdd\config.yaml" $configContent
Write-Success "config.yaml updated"

# ─────────────────────────────────────────────
# Update AGENTS.md header
# ─────────────────────────────────────────────
Write-Header "Updating context/AGENTS.md..."

$agentsContent = Get-Content "context\AGENTS.md" -Raw
$agentsContent = $agentsContent -replace "\[Source Language / Framework\] \(located in ``source/``\)", "$SourceFramework ($SourceLang) (located in ``source/``)"
$agentsContent = $agentsContent -replace "\[Target Language / Framework\] \(output goes in ``output/``\)", "$TargetFramework ($TargetLang) (output goes in ``output/``)"
Set-Content "context\AGENTS.md" $agentsContent
Write-Success "AGENTS.md updated with project details"

# ─────────────────────────────────────────────
# Create output folder scaffold
# ─────────────────────────────────────────────
Write-Header "Creating output/ folder scaffold..."

$outputDirs = @(
    "output"
)

foreach ($dir in $outputDirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}
Write-Success "output/ folder ready"

# ─────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "   ✅ AlihSpec Framework Initialized!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host ""
Write-Host "  Project : $ProjectName" -ForegroundColor White
Write-Host "  From    : $SourceFramework ($SourceLang)" -ForegroundColor Blue
Write-Host "  To      : $TargetFramework ($TargetLang)" -ForegroundColor Green
Write-Host "  Preset  : $presetKey" -ForegroundColor White
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Yellow
Write-Host "  1. Copy your source project to source/" -ForegroundColor White
Write-Host "  2. Open context/AGENTS.md and fill in Source Project Notes" -ForegroundColor White
Write-Host "  3. Read context/checklist-before-start.md" -ForegroundColor White
Write-Host "  4. For vibe coding: open context/VIBE.md and copy the Quick Start prompt" -ForegroundColor White
Write-Host ""
